function make_distance_matrix_standalone(refCifti, midthickSurfs, outMatFile, varargin)
%MAKE_DISTANCE_MATRIX_STANDALONE Build a MATLAB DistanceMatrix.mat file.
%
%   make_distance_matrix_standalone(refCifti, {leftSurf, rightSurf}, outMatFile)
%
% This is a standalone, cleaned-up replacement for the legacy
% make_distance_matrix.m. It writes a v7.3 MAT file containing variable D.
%
% Required inputs:
%   refCifti       CIFTI path or an already-loaded ft_read_cifti_mod struct.
%                  Path input requires ft_read_cifti_mod on the MATLAB path.
%   midthickSurfs  {left_midthickness.surf.gii, right_midthickness.surf.gii}
%   outMatFile     Output .mat path. If no extension is supplied, .mat is used.
%
% Optional name/value pairs:
%   'NWorkers'              Parallel workers for geodesic rows. Default: 1
%   'WorkbenchCommand'      Workbench command. Default: 'wb_command'
%   'TempDir'               Temporary directory. Default: tempname
%   'InterhemisphericMode'  'constant' or 'euclidean'. Default: 'constant'
%   'EuclideanChunkRows'    Rows per Euclidean-distance chunk. Default: 256
%   'SaveCortexOnly'        Also save DistanceMatrixCortexOnly.mat. Default: false
%   'Force'                 Overwrite output file. Default: false
%
% Notes:
%   - 'constant' interhemispheric mode matches the old MATLAB builder, where
%     cross-hemisphere cortical distances saturated to uint8(255).
%   - The current Python pipeline uses DistanceMatrix.npy. If that file exists,
%     convert_distance_npy_to_mat is preferred because it preserves the exact
%     matrix generated by the current pipeline.

p = inputParser;
p.addRequired('refCifti');
p.addRequired('midthickSurfs', @(x) iscell(x) && numel(x) == 2);
p.addRequired('outMatFile', @(x) ischar(x) || isstring(x));
p.addParameter('NWorkers', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1);
p.addParameter('WorkbenchCommand', 'wb_command', @(x) ischar(x) || isstring(x));
p.addParameter('TempDir', '', @(x) ischar(x) || isstring(x));
p.addParameter('InterhemisphericMode', 'constant', @(x) any(strcmpi(char(x), {'constant','euclidean'})));
p.addParameter('EuclideanChunkRows', 256, @(x) isnumeric(x) && isscalar(x) && x >= 1);
p.addParameter('SaveCortexOnly', false, @(x) islogical(x) || isnumeric(x));
p.addParameter('Force', false, @(x) islogical(x) || isnumeric(x));
p.parse(refCifti, midthickSurfs, outMatFile, varargin{:});

nWorkers = double(p.Results.NWorkers);
wbCommand = char(p.Results.WorkbenchCommand);
tempDir = char(p.Results.TempDir);
interhemiMode = lower(char(p.Results.InterhemisphericMode));
euclideanChunkRows = double(p.Results.EuclideanChunkRows);
saveCortexOnly = logical(p.Results.SaveCortexOnly);
force = logical(p.Results.Force);
outMatFile = char(p.Results.outMatFile);

[outDir, ~, outExt] = fileparts(outMatFile);
if isempty(outExt)
    outMatFile = [outMatFile '.mat'];
end
if isempty(outDir)
    outDir = pwd;
end
if ~exist(outDir, 'dir')
    mkdir(outDir);
end
if exist(outMatFile, 'file')
    if force
        delete(outMatFile);
    else
        error('Output file already exists: %s. Use ''Force'', true to overwrite.', outMatFile);
    end
end

if isempty(tempDir)
    tempDir = tempname(outDir);
end
if ~exist(tempDir, 'dir')
    mkdir(tempDir);
end
cleanupTemp = onCleanup(@() local_rmdir_quiet(tempDir));

if ischar(refCifti) || isstring(refCifti)
    if exist('ft_read_cifti_mod', 'file') ~= 2
        error('Path input for refCifti requires ft_read_cifti_mod on the MATLAB path.');
    end
    ref = ft_read_cifti_mod(char(refCifti));
else
    ref = refCifti;
end
if isfield(ref, 'data')
    ref.data = [];
end
if ~isfield(ref, 'brainstructure') || ~isfield(ref, 'pos')
    error('refCifti must contain brainstructure and pos fields, as returned by ft_read_cifti_mod.');
end

leftSurf = char(midthickSurfs{1});
rightSurf = char(midthickSurfs{2});
LH = gifti(leftSurf);
RH = gifti(rightSurf);

nLeftSurf = size(LH.vertices, 1);
nRightSurf = size(RH.vertices, 1);
brainstructure = ref.brainstructure(:);

leftMask = brainstructure(1:nLeftSurf) ~= -1;
rightMask = brainstructure((nLeftSurf + 1):(nLeftSurf + nRightSurf)) ~= -1;
leftVerts0 = find(leftMask) - 1;
rightVerts0 = find(rightMask) - 1;

fprintf('Left cortex vertices: %d\n', numel(leftVerts0));
fprintf('Right cortex vertices: %d\n', numel(rightVerts0));

poolCreated = false;
if nWorkers > 1
    pool = gcp('nocreate');
    if isempty(pool)
        parpool('local', nWorkers);
        poolCreated = true;
    end
end
cleanupPool = onCleanup(@() local_delete_pool_if_created(poolCreated));

fprintf('Computing left-hemisphere geodesic block...\n');
leftBlock = local_geodesic_block(wbCommand, leftSurf, leftVerts0, leftMask, tempDir, 'L', nWorkers);

fprintf('Computing right-hemisphere geodesic block...\n');
rightBlock = local_geodesic_block(wbCommand, rightSurf, rightVerts0, rightMask, tempDir, 'R', nWorkers);

nLeft = size(leftBlock, 1);
nRight = size(rightBlock, 1);
nCort = nLeft + nRight;

if saveCortexOnly
    D = local_cortex_matrix(leftBlock, rightBlock, interhemiMode);
    cortexFile = fullfile(outDir, 'DistanceMatrixCortexOnly.mat');
    if exist(cortexFile, 'file') && force
        delete(cortexFile);
    end
    save(cortexFile, 'D', '-v7.3');
    clear D;
end

surfaceCoords = [LH.vertices; RH.vertices];
surfaceIndex = brainstructure > 0 & brainstructure < 3;
surfaceIndex = surfaceIndex(1:size(surfaceCoords, 1));
surfaceCoords = surfaceCoords(surfaceIndex, :);
subcorticalCoords = ref.pos(brainstructure > 2, :);
allCoords = double([surfaceCoords; subcorticalCoords]);
nAll = size(allCoords, 1);

fprintf('Computing Euclidean distances in chunks (%d grayordinates)...\n', nAll);
D = zeros(nAll, nAll, 'uint8');
for rowStart = 1:euclideanChunkRows:nAll
    rowStop = min(rowStart + euclideanChunkRows - 1, nAll);
    rows = rowStart:rowStop;
    D(rows, :) = local_uint8_euclidean(allCoords(rows, :), allCoords);
    fprintf('  rows %d-%d / %d\n', rowStart, rowStop, nAll);
end

D(1:nLeft, 1:nLeft) = leftBlock;
D((nLeft + 1):nCort, (nLeft + 1):nCort) = rightBlock;
if strcmp(interhemiMode, 'constant')
    D(1:nLeft, (nLeft + 1):nCort) = uint8(255);
    D((nLeft + 1):nCort, 1:nLeft) = uint8(255);
end
D(1:(nAll + 1):end) = uint8(0);

fprintf('Saving %s...\n', outMatFile);
save(outMatFile, 'D', '-v7.3');
fprintf('Done. Output variable: D (%d x %d uint8)\n', nAll, nAll);
end

function D = local_cortex_matrix(leftBlock, rightBlock, interhemiMode)
nLeft = size(leftBlock, 1);
nRight = size(rightBlock, 1);
D = zeros(nLeft + nRight, nLeft + nRight, 'uint8');
D(1:nLeft, 1:nLeft) = leftBlock;
D((nLeft + 1):end, (nLeft + 1):end) = rightBlock;
if strcmp(interhemiMode, 'constant')
    D(1:nLeft, (nLeft + 1):end) = uint8(255);
    D((nLeft + 1):end, 1:nLeft) = uint8(255);
end
end

function block = local_geodesic_block(wbCommand, surfFile, verts0, cortexMask, tempDir, hemiTag, nWorkers)
nRows = nnz(cortexMask);
nCols = numel(verts0);
block = zeros(nRows, nCols, 'uint8');

if nWorkers > 1
    parfor i = 1:nCols
        block(:, i) = local_geodesic_column(wbCommand, surfFile, verts0(i), cortexMask, tempDir, hemiTag, i);
    end
else
    for i = 1:nCols
        block(:, i) = local_geodesic_column(wbCommand, surfFile, verts0(i), cortexMask, tempDir, hemiTag, i);
        if mod(i, 500) == 0 || i == nCols
            fprintf('  %s columns %d / %d\n', hemiTag, i, nCols);
        end
    end
end
end

function col = local_geodesic_column(wbCommand, surfFile, vertex0, cortexMask, tempDir, hemiTag, idx)
tmpFile = fullfile(tempDir, sprintf('%s_%06d.shape.gii', hemiTag, idx));
cmd = sprintf('"%s" -surface-geodesic-distance "%s" %d "%s"', wbCommand, surfFile, vertex0, tmpFile);
[status, msg] = system(cmd);
if status ~= 0
    error('wb_command failed for %s vertex %d: %s', hemiTag, vertex0, msg);
end
g = gifti(tmpFile);
delete(tmpFile);
col = uint8(g.cdata(cortexMask));
end

function D = local_uint8_euclidean(A, B)
A = double(A);
B = double(B);
A2 = sum(A .* A, 2);
B2 = sum(B .* B, 2)';
D2 = bsxfun(@plus, A2, B2) - 2 .* (A * B');
D2(D2 < 0) = 0;
D = uint8(min(round(sqrt(D2)), 255));
end

function local_rmdir_quiet(pathToRemove)
if exist(pathToRemove, 'dir')
    [~, ~] = rmdir(pathToRemove, 's');
end
end

function local_delete_pool_if_created(poolCreated)
if poolCreated
    pool = gcp('nocreate');
    if ~isempty(pool)
        delete(pool);
    end
end
end
